# Generated by Django 6.0.4 on 2026-05-10 07:43

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='struggles',
        ),
        migrations.RemoveField(
            model_name='profile',
            name='weight_goal',
        ),
        migrations.AddField(
            model_name='food',
            name='ingredients',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='profile',
            name='activity_level',
            field=models.CharField(choices=[('sedentary', 'Sedentary'), ('moderate', 'Moderate'), ('active', 'Active')], default='exit', max_length=50),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='profile',
            name='age',
            field=models.PositiveIntegerField(null=True),
        ),
        migrations.AddField(
            model_name='profile',
            name='blood_type',
            field=models.CharField(blank=True, max_length=10),
        ),
        migrations.AddField(
            model_name='profile',
            name='current_weight',
            field=models.FloatField(null=True),
        ),
        migrations.AddField(
            model_name='profile',
            name='dietary_restrictions',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='profile',
            name='height',
            field=models.FloatField(null=True),
        ),
        migrations.AddField(
            model_name='profile',
            name='illness_history',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='profile',
            name='medications',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='profile',
            name='target_weight',
            field=models.FloatField(null=True),
        ),
        migrations.AlterField(
            model_name='group',
            name='wellness_advice',
            field=models.TextField(help_text='General feedback for this group'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='group',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='main_app.group'),
        ),
        migrations.CreateModel(
            name='DefaultPlan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(choices=[('weight_loss', 'Weight Loss'), ('muscle_gain', 'Muscle Gain'), ('maintenance', 'Maintenance')], max_length=20, unique=True)),
                ('base_foods', models.ManyToManyField(to='main_app.food')),
            ],
        ),
        migrations.CreateModel(
            name='NutritionPlan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('daily_calorie_target', models.PositiveIntegerField()),
                ('special_notes', models.TextField(blank=True)),
                ('customized_foods', models.ManyToManyField(to='main_app.food')),
                ('parent_plan', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='main_app.defaultplan')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.DeleteModel(
            name='Nutrition_plan',
        ),
    ]
